export const mockJobs = [
  {
    id: '1',
    title: 'Senior Product Manager',
    department: 'Product',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$180K - $220K',
    postedDate: '2024-03-15',
    deadline: '2024-04-15',
    description: 'We are looking for an experienced Product Manager to lead our platform initiatives.',
    requirements: ['5+ years PM experience', 'B2B SaaS background', 'Leadership experience'],
    applicants: 24,
    status: 'open',
  },
  {
    id: '2',
    title: 'Frontend Engineer',
    department: 'Engineering',
    location: 'Remote',
    type: 'Full-time',
    salary: '$160K - $200K',
    postedDate: '2024-03-10',
    deadline: '2024-04-10',
    description: 'Join our engineering team to build amazing user experiences with React and Next.js.',
    requirements: ['3+ years React experience', 'TypeScript proficiency', 'Git experience'],
    applicants: 42,
    status: 'open',
  },
  {
    id: '3',
    title: 'Data Analyst',
    department: 'Analytics',
    location: 'New York, NY',
    type: 'Full-time',
    salary: '$120K - $150K',
    postedDate: '2024-02-28',
    deadline: '2024-03-28',
    description: 'Help us drive data-informed decisions across the organization.',
    requirements: ['2+ years analytics experience', 'SQL proficiency', 'Tableau or Power BI'],
    applicants: 18,
    status: 'closed',
  },
];

export const mockCandidates = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah.chen@email.com',
    phone: '(555) 123-4567',
    position: 'Senior Product Manager',
    appliedDate: '2024-03-20',
    status: 'screening',
    cvScore: 85,
    resumeUrl: '#',
    notes: 'Strong background in B2B SaaS. Graduated from Stanford.',
  },
  {
    id: '2',
    name: 'Michael Rodriguez',
    email: 'michael.r@email.com',
    phone: '(555) 234-5678',
    position: 'Senior Product Manager',
    appliedDate: '2024-03-18',
    status: 'interview',
    cvScore: 92,
    interviewScore: 88,
    resumeUrl: '#',
    notes: 'Led product teams at tech startups. Excellent communication skills.',
  },
  {
    id: '3',
    name: 'Emma Wilson',
    email: 'emma.wilson@email.com',
    phone: '(555) 345-6789',
    position: 'Frontend Engineer',
    appliedDate: '2024-03-19',
    status: 'screening',
    cvScore: 78,
    resumeUrl: '#',
    notes: 'Passionate about performance optimization.',
  },
  {
    id: '4',
    name: 'James Park',
    email: 'james.park@email.com',
    phone: '(555) 456-7890',
    position: 'Frontend Engineer',
    appliedDate: '2024-03-17',
    status: 'offer',
    cvScore: 94,
    interviewScore: 91,
    resumeUrl: '#',
    notes: 'Outstanding technical skills and team fit.',
  },
  {
    id: '5',
    name: 'Lisa Anderson',
    email: 'lisa.a@email.com',
    phone: '(555) 567-8901',
    position: 'Frontend Engineer',
    appliedDate: '2024-03-16',
    status: 'rejected',
    cvScore: 65,
    resumeUrl: '#',
    notes: 'Lacking required React experience.',
  },
];

export const mockKPIs = [
  { label: 'Total Applicants', value: '247', change: 12, trend: 'up' },
  { label: 'Positions Open', value: '8', change: 2, trend: 'down' },
  { label: 'Avg Time to Hire', value: '32 days', change: 5, trend: 'down' },
  { label: 'Offer Acceptance', value: '78%', change: 3, trend: 'up' },
];